### ISSUE TITLE
Paneau de reauthentification sous la sticky bar

### ISSUE THREAD

**Issue by salimkanoun** [salimkanoun/GaelO_Frontend#104]
y a un problem de Z index et surtout faut baisser le panneau de reauthentification ou mieux le mettre au centre

**Comment by salimkanoun** [comment]
en fait tous les modaux sont sous la sticky bar dans quand t'a la croix de fermeture qui chevauchent la sticky bar tu peux pas cliquer dessus.

Faut resoudre le probleme de Z index (car le modal pour etre vraiement doit empecher d'interagir avec la bar) et aussi je pense qu'il faut allouer l'espace a la stikybar et que tous les autre compsant décendent 50/100 pixel pour ne pas avoir de chevauchement je crois avoir fait ca dans le css de OrthancToolsJS

**Comment by salimkanoun** [comment]
je crois que c'est ca mon CSS qui gerait ca dans orthanc tool js

.app{
	padding-top: 100px !important;
	padding: 50px;
	background-image:  url(./images/wallpaper.jpg);
}

**Comment by salimkanoun** [comment]
et dans la div de reauthentifacation in manque l'arrondi sur son background blanc ce qui fait qu'il y a les petits coins blanc en bordure en haut

**Comment by EmilieOLIVIE** [comment]
See #109
