### ISSUE TITLE
Tree enhancement

### ISSUE THREAD

**Issue by EmilieOLIVIE** [salimkanoun/GaelO_Frontend#115]
Fonctionnalités à ajouter:
- Recherche par nom (+autres critères?)
- Couleur des visits selon status (et selon user role)
- Filtre par status/couleur? (voir possibilité d'implémentation)

**Comment by EmilieOLIVIE** [comment]
> Filtre par status/couleur? (voir possibilité d'implémentation)
Cf issue #17

**Comment by salimkanoun** [comment]
@EmilieOLIVIE  faudrait faire cette fonctionalité en priorité pour pouvoir livrer une version de test,
Pour l'instant faut rester sur le meme type de fonctionalité que la V1
=> Filtrer par chaine de caractere via l'input text
=> filter avec un click droit ou un menu filtre sur le statut des visites (adapté a chaque role  pour investigateur => les visit en attente d'upload image ou investigator form, pour controller filtrer visits en QC Not Done ou Awaiting definitive conclusion)
