### ISSUE TITLE
Visites Not Done sélectionnable?

### ISSUE THREAD

**Issue by EmilieOLIVIE** [salimkanoun/GaelO_Frontend#144]
Rendre les visites Not Done non sélectionnable dans le tree et visitTable ? (interface d'une telle visite = patientInformation...)

**Comment by salimkanoun** [comment]
@EmilieOLIVIE oui je pense que c'est une bonne idée si tu peux mettre les item visite not done en disable avec un tooltip ou info bulle qui dit "Visit Not Done" au survol.
