### ISSUE TITLE
Visit Interface : Mettre les If ici

### ISSUE THREAD

**Issue by salimkanoun** [salimkanoun/GaelO_Frontend#150]
Il faut gérer les affichage ou non affichage des modules Dicom, Corrective action, Qc, Investigator form dans ce composant Visit Interface.
lui connait le statut de la visite et instancie ou non les composant qui doivent afficher les information suivant le statut des visits.

Comme ca tout tes IF dans les render de ces sous composant disparaittront car ils seront gérés dans Visitinterface

**Comment by salimkanoun** [comment]
this.props.uploader => pareil ici pas besoin de faire passer en props,
Faut faire passer tout le statut de la visit a visit interface et suivant le statut et le role il choisir d'instancier ou pas le composant uploader

**Comment by EmilieOLIVIE** [comment]
Voir 790b53051dc9f79c17cf840046777ee7ab1a64f6
