### ISSUE TITLE
Mettre un loading le temps qu'on recupère l'info du back

### ISSUE THREAD

**Issue by salimkanoun** [salimkanoun/GaelO_Frontend#163]
Pour les div visit et patient, mieux de mettre un loading le temps qu'on recupere les info du back pour eviter les refresh 

https://www.davidhu.io/react-spinners/

https://codesandbox.io/s/mqx0ql55qp

**Comment by EmilieOLIVIE** [comment]
3f523bdf40af893e3fd6f7df9828f2d1f8db0cf2 refers to fix on #161
