### ISSUE TITLE
Injected Time Vs DateTime

### ISSUE THREAD

**Issue by salimkanoun** [salimkanoun/GaelO_Frontend#43]
Pour + tard,

Dans Interfaces données dicoms
si Injected DateTime est null alors afficher l'injected Time (avec un note "assumed same day")

**Comment by salimkanoun** [comment]
Quand tu fera la table des dicoms details

**Comment by EmilieOLIVIE** [comment]
Voir commit [ "#100 almost done #47 fixed"](https://github.com/salimkanoun/GaelO_Frontend/commit/4d296a1915debcf0daebe8a726403c2789dd5a63) (typo sur ref 47 au lieu de 43)
