### ISSUE TITLE
Roles pas sur /api/studies + select automatique

### ISSUE THREAD

**Issue by salimkanoun** [salimkanoun/GaelO_Frontend#91]
pour fill le select de studies tu appelle GET /api/studies
mais cette route n'est que pour l'administrateur, l'utilisateur lambda n'est pas sencé lister toute les etudes connues de la plateforme (et si tu le fais d'un utilisateur non admin tu aura un 403)

Il faut appeler les roles de l'utilisateur courrant via : 
users/{id}/roles/
pour récupérer les Study / Role map a afficher dans le select

Si il n'y a qu'un choix dans le select Study ou dans le select Role alors il faut l'activer automatiquement. 
Du coup si il n'y a qu'un choix dans study ET dans role ca revient a activer automatiquement ce role.

**Comment by EmilieOLIVIE** [comment]
Reste à faire 

> Si il n'y a qu'un choix dans le select Study ou dans le select Role alors il faut l'activer automatiquement.
Du coup si il n'y a qu'un choix dans study ET dans role ca revient a activer automatiquement ce role.
