### ISSUE TITLE
Sticky navbar

### ISSUE THREAD

**Issue by salimkanoun** [salimkanoun/GaelO_Frontend#92]
La sticky navbar que t'a mis dans ton TODO est une bonne idée

Tu peux regarder dans OrthancToolsJS j'ai fait un truc similaire (mais je sais plus comment) avec une bar qui change de couleur quand elle se détache du top.

et y a un probleme d'affichage, le panel central chevauche le bas de la bar, il faudrait plus d'espace entre la bar et le pannel central (voir OrthancToolsJS on l'avait plutot reussi de coté la)

**Comment by EmilieOLIVIE** [comment]
Voir pour le listener

**Comment by EmilieOLIVIE** [comment]
Change jumbotron position + fix background wallpaper
