### ISSUE TITLE
Pourquoi ne pas appeler creatable visit au mount de new visit ? 

### ISSUE THREAD

**Issue by salimkanoun** [salimkanoun/GaelO_Frontend#95]
Actuellement l'API creatable-visit est appelé au moment de l'affichage de visit.
Or tu n'en a besoin qu'au moment de créer une visit, tu peux pas le mettre dans componentDidMount du composant de creation de visite ?

**Comment by EmilieOLIVIE** [comment]
Je le fais au moment de l'affichage de l'interface de visit pour savoir si je dois afficher le bouton permettant de créer une visit. Si le patient donné n'a aucune visite attendant d'être créé, je ne permets pas la création.

**Comment by salimkanoun** [comment]
Ah oui exact, très bien
